"""User-started native builds of the trusted wrapper, never agent-authored scripts."""
import hashlib
import importlib.util
import json
import os
from pathlib import Path
import platform
import re
import shutil
import signal
import stat
import subprocess
import threading
import time
from types import SimpleNamespace
import uuid
import zipfile

from . import agent, config, db, files, sandbox

# Reads the upload key from the environment. Nothing here is written to a file that
# outlives the build, and no password appears in a Gradle task argument.
SIGNING_GRADLE = """// Generated by Local Foundry. Do not commit signing material.
android {
    signingConfigs {
        foundryUpload {
            storeFile file(System.getenv("FOUNDRY_KEYSTORE"))
            storePassword System.getenv("FOUNDRY_STORE_PASSWORD")
            keyAlias System.getenv("FOUNDRY_KEY_ALIAS")
            keyPassword System.getenv("FOUNDRY_KEY_PASSWORD")
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.foundryUpload
            minifyEnabled false
        }
    }
}
"""

MAX_ARTIFACT = 512 * 1024 * 1024
BUILD_SECONDS = 1800
MAX_LOG = 80_000


def generator():
    spec = importlib.util.spec_from_file_location('foundry_mobile_generator', config.ROOT / 'scripts/mobile.py')
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def build_environment(work=None):
    # Xcode uses the user's configured signing keychain. Provider keys, npm tokens,
    # NODE_OPTIONS, Java injection flags and global Gradle init scripts are omitted.
    env = {key: value for key, value in os.environ.items()
           if key in {'PATH', 'HOME', 'USER', 'TMPDIR', 'JAVA_HOME', 'ANDROID_HOME',
                      'ANDROID_SDK_ROOT', 'DEVELOPER_DIR', 'LANG', 'LC_ALL',
                      'HTTP_PROXY', 'HTTPS_PROXY', 'NO_PROXY', 'http_proxy', 'https_proxy', 'no_proxy'}}
    env.update(CI='true', CAPACITOR_TELEMETRY_DISABLED='1', GIT_TERMINAL_PROMPT='0',
               npm_config_userconfig=os.devnull,
               npm_config_ignore_scripts='true', npm_config_audit='false', npm_config_fund='false')
    if work:
        # Separate from the user's Gradle settings/credentials/init scripts.
        env['GRADLE_USER_HOME'] = str(work / '.gradle-home')
        env['npm_config_cache'] = str(work / '.npm-cache')
        env['npm_config_globalconfig'] = str(work / '.npm-globalrc')
        # Keep the debug signing key between builds so Android can install updates.
        signing = work.parent.parent / 'android-signing'
        if signing.is_symlink():
            raise ValueError('Android signing directory must not be linked.')
        signing.mkdir(mode=0o700, exist_ok=True)
        env['ANDROID_USER_HOME'] = str(signing)
    return env


def version(program, arguments, pattern):
    try:
        result = subprocess.run([program, *arguments], env=build_environment(), capture_output=True,
                                text=True, timeout=8, check=False)
        match = re.search(pattern, result.stdout + result.stderr)
        return int(match[1]) if result.returncode == 0 and match else 0
    except (OSError, subprocess.TimeoutExpired):
        return 0


def android_sdk():
    candidates = [os.environ.get('ANDROID_HOME'), os.environ.get('ANDROID_SDK_ROOT'),
                  str(Path.home() / 'Android/Sdk'), str(Path.home() / 'Library/Android/sdk')]
    return next((Path(p).expanduser().resolve() for p in candidates if p and Path(p).expanduser().is_dir()), None)


def capabilities():
    common = []
    if config.OFFLINE_ONLY:
        common.append('Mobile compilation downloads native dependencies. Restart with offline-only mode disabled to build.')
    if platform.system() not in {'Linux', 'Darwin'}:
        common.append('Run the builder in WSL2 on Windows, or on macOS.')
    node, npm = shutil.which('node'), shutil.which('npm')
    if not node or version(node, ['--version'], r'v(\d+)') < 22:
        common.append('Install Node.js 22 or newer in the builder environment.')
    if not npm:
        common.append('Install npm in the builder environment.')
    android = list(common)
    java = shutil.which('java')
    if not java or version(java, ['-version'], r'version "(\d+)') < 21:
        android.append('Install JDK 21 or newer in the builder environment.')
    sdk = android_sdk()
    if not sdk or not (sdk / 'platforms/android-36/android.jar').is_file():
        android.append('Install Android SDK platform 36 and set ANDROID_HOME; on Windows use the Linux SDK inside WSL.')
    if not sdk or not list(sdk.glob('build-tools/*/apksigner')):
        android.append('Install Android SDK build-tools (including apksigner) and accept the SDK licenses.')
    # A Play release is an AAB signed with an upload key, so it needs everything a
    # debug APK needs plus jarsigner, which verifies bundle signatures (apksigner
    # only handles APKs).
    bundle = list(android)
    if not shutil.which('jarsigner'):
        bundle.append('Install a full JDK providing jarsigner; a JRE alone cannot verify a signed bundle.')
    ios = list(common)
    if platform.system() != 'Darwin':
        ios.append('IPA builds require this builder running on macOS with Xcode. Windows/WSL cannot build an IPA locally.')
    elif not shutil.which('xcodebuild') or version('xcodebuild', ['-version'], r'Xcode (\d+)') < 26:
        ios.append('Install and select Xcode 26 or newer, then complete its first-launch setup.')
    if platform.system() == 'Darwin' and not shutil.which('codesign'):
        ios.append('Install the Xcode command-line tools.')
    return {'apk': {'available': not android, 'blockers': android, 'label': 'Android testing APK'},
            'aab': {'available': not bundle, 'blockers': bundle, 'label': 'Play Store app bundle'},
            'ipa': {'available': not ios, 'blockers': ios, 'label': 'Signed iOS IPA'}}


# JKS starts 0xFEEDFEED; PKCS#12 is a DER SEQUENCE. Checking here turns "you pointed
# at the wrong file" into a clear message instead of a Gradle keystore exception, and
# means an arbitrary host path is never handed to the build tool.
KEYSTORE_MAGIC = (b'\xfe\xed\xfe\xed', b'\x30\x82')
MAX_KEYSTORE = 1024 * 1024


def validate_icon_source(data):
    """Optional, but when given it must be a real square image on this machine."""
    raw = str(data.get('icon_source', '')).strip()
    if not raw:
        return {'icon_source': '', 'icon_background': '#FFFFFF'}
    path = Path(raw).expanduser()
    if not path.is_absolute():
        raise ValueError('Give the full path to the icon image.')
    if path.is_symlink() or any(parent.is_symlink() for parent in path.parents):
        raise ValueError('The icon path must not contain a symbolic link.')
    gen = generator()
    try:
        gen.load_source(path)
        background = gen.parse_colour(data.get('icon_background') or '#FFFFFF')
    except gen.InvalidInput as exc:
        raise ValueError(str(exc)) from None
    return {'icon_source': str(path.resolve()), 'icon_background': '#%02X%02X%02X' % background}


def validate_keystore(data):
    """Locate and sanity-check the upload key. Passwords are never written to the
    build record, never placed in argv, and are redacted out of the build log."""
    raw = str(data.get('keystore_path', '')).strip()
    if not raw:
        raise ValueError('Select the keystore holding your Play upload key.')
    path = Path(raw).expanduser()
    if not path.is_absolute():
        raise ValueError('Give the full path to the keystore file.')
    if path.is_symlink() or any(parent.is_symlink() for parent in path.parents):
        raise ValueError('The keystore path must not contain a symbolic link.')
    if not path.is_file():
        raise ValueError('No keystore file at that path.')
    size = path.stat().st_size
    if not 0 < size <= MAX_KEYSTORE:
        raise ValueError('That file is not a keystore (expected a small .jks or .p12 file).')
    with path.open('rb') as stream:
        if not stream.read(4).startswith(KEYSTORE_MAGIC):
            raise ValueError('That file is not a Java keystore or PKCS#12 file. '
                             'Create one with keytool; see MOBILE.md.')
    alias = str(data.get('key_alias', '')).strip()
    if not re.fullmatch(r'[A-Za-z0-9._-]{1,64}', alias):
        raise ValueError('Enter the key alias used when the keystore was created.')
    store_password = str(data.get('store_password', ''))
    key_password = str(data.get('key_password', '')) or store_password
    if not 6 <= len(store_password) <= 200 or not 6 <= len(key_password) <= 200:
        raise ValueError('Keystore passwords must be 6–200 characters.')
    return {'keystore_path': str(path.resolve()), 'key_alias': alias,
            'store_password': store_password, 'key_password': key_password}


def validate_request(body):
    data = dict(body)
    gen = generator()
    try:
        for key, check in [('origin', gen.validate_origin), ('app_id', gen.validate_app_id),
                           ('name', gen.validate_name), ('version', gen.validate_version)]:
            data[key] = check(data[key])
    except gen.InvalidInput as exc:
        raise ValueError(str(exc)) from None
    if data['target'] not in {'apk', 'aab', 'ipa'}:
        raise ValueError('Choose APK, AAB or IPA.')
    if config.OFFLINE_ONLY or not data.get('allow_network'):
        raise ValueError('Mobile builds require online mode and permission to download native build dependencies.')
    if data['target'] == 'ipa' and not re.fullmatch(r'[A-Z0-9]{10}', data.get('team_id', '')):
        raise ValueError('Enter your 10-character Apple Developer Team ID. Configure signing in Xcode first.')
    data.update(validate_icon_source(data))
    if data['target'] == 'aab':
        data.update(validate_keystore(data))
    else:
        # Signing material is only ever carried for the build that needs it.
        for key in ('keystore_path', 'key_alias', 'store_password', 'key_password'):
            data.pop(key, None)
    blockers = capabilities()[data['target']]['blockers']
    if blockers:
        raise ValueError(' '.join(blockers))
    return data


def directory(project_id, build_id=None):
    root = sandbox.project_dir(project_id) / 'mobile-builds'
    if root.is_symlink():
        raise ValueError('Mobile build directory must not be linked.')
    if build_id:
        sandbox.validate_id(build_id)
        root /= build_id
        if root.is_symlink():
            raise ValueError('Mobile build directory must not be linked.')
    return root


def write_record(folder, record):
    temporary = folder / (uuid.uuid4().hex + '.partial')
    fd = os.open(temporary, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(fd, 'w') as stream:
        json.dump(record, stream, indent=2)
    os.replace(temporary, folder / 'build.json')


def get(project_id, build_id):
    path = directory(project_id, build_id) / 'build.json'
    if path.is_symlink() or not path.is_file() or path.stat().st_size > 32_000:
        raise ValueError('Mobile build not found.')
    item = json.loads(path.read_text())
    if item.get('id') != build_id or item.get('project_id') != project_id:
        raise ValueError('Mobile build not found.')
    if item['status'] == 'running':
        run = db.query('SELECT status FROM runs WHERE id=%s', (build_id,), one=True)
        if not run or run['status'] != 'running':
            item.update(status='interrupted', phase='Interrupted; start a new build.')
    return item


def listing(project_id):
    root = directory(project_id)
    if not root.exists():
        return []
    rows = []
    for path in root.iterdir():
        if re.fullmatch(r'[0-9a-f]{32}', path.name) and path.is_dir() and not path.is_symlink():
            try:
                rows.append(get(project_id, path.name))
            except (OSError, ValueError, KeyError):
                continue
    return sorted(rows, key=lambda row: row['created_at'], reverse=True)[:50]


def check_cancel(cancelled):
    if cancelled.is_set():
        raise InterruptedError('Mobile build cancelled. No artifact was published.')


def command(argv, cwd, env, cancelled, deadline, log_path, secrets=()):
    """Fixed argv only; terminate the process group on cancellation or timeout.

    `secrets` are removed from anything written to the build log or raised in an
    error. Signing passwords travel in the environment rather than argv because
    /proc/<pid>/cmdline is world-readable while /proc/<pid>/environ is not.
    """
    check_cancel(cancelled)
    if time.monotonic() >= deadline:
        raise RuntimeError('Mobile build exceeded the 30-minute limit.')
    tail = bytearray()
    proc = subprocess.Popen([str(x) for x in argv], cwd=cwd, env=env, stdin=subprocess.DEVNULL,
                            stdout=subprocess.PIPE, stderr=subprocess.STDOUT, start_new_session=True)
    def read():
        while chunk := proc.stdout.read(4096):
            tail.extend(chunk)
            if len(tail) > MAX_LOG:
                del tail[:-MAX_LOG]
    reader = threading.Thread(target=read, daemon=True)
    reader.start()
    try:
        while proc.poll() is None:
            check_cancel(cancelled)
            if time.monotonic() >= deadline:
                raise RuntimeError('Mobile build exceeded the 30-minute limit.')
            cancelled.wait(.2)
        check_cancel(cancelled)
    finally:
        # Gradle uses --no-daemon, but also kill any child still alive in the group.
        try:
            os.killpg(proc.pid, signal.SIGKILL)
        except ProcessLookupError:
            pass
        proc.wait()
        reader.join(timeout=3)
        text = agent.redact(bytes(tail).decode(errors='replace'))
        for secret in secrets:
            if secret:
                text = text.replace(secret, '[redacted signing secret]')
        previous = log_path.read_text() if log_path.exists() else ''
        log_path.write_text((previous + '\n' + text)[-MAX_LOG:])
        log_path.chmod(0o600)
        proc.stdout.close()
    if proc.returncode:
        raise RuntimeError(text[-2500:] or f'Native build command exited {proc.returncode}.')


def file_hash(path):
    digest = hashlib.sha256()
    with path.open('rb') as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b''):
            digest.update(chunk)
    return digest.hexdigest()


def inspect_artifact(path, target):
    if path.is_symlink() or not path.is_file() or not 0 < path.stat().st_size <= MAX_ARTIFACT:
        raise ValueError('No valid native artifact was produced (maximum 512 MiB).')
    with zipfile.ZipFile(path) as archive:
        names = set(archive.namelist())
        if target == 'apk':
            valid = {'AndroidManifest.xml', 'classes.dex'} <= names
        elif target == 'aab':
            # A bundle keeps its manifest in protobuf under base/, and an upload-key
            # signature lives in META-INF. Both must be present or Play rejects it.
            valid = ({'BundleConfig.pb', 'base/manifest/AndroidManifest.xml'} <= names
                     and any(name.startswith('META-INF/') and name.endswith(('.RSA', '.EC', '.DSA'))
                             for name in names))
        else:
            apps = [name[:-len('Info.plist')] for name in names
                    if re.fullmatch(r'Payload/[^/]+[.]app/Info[.]plist', name)]
            valid = len(apps) == 1 and apps[0] + '_CodeSignature/CodeResources' in names
        if not valid:
            raise ValueError('The build output is not the requested APK, signed AAB or signed IPA package.')


def artifact(project_id, build_id):
    item = get(project_id, build_id)
    if item['status'] != 'completed':
        raise ValueError('This mobile build has no completed artifact.')
    target = item['target']
    if target not in {'apk', 'aab', 'ipa'}:
        raise ValueError('Invalid mobile artifact type.')
    path = directory(project_id, build_id) / ('app.' + target)
    mode = path.lstat() if path.exists() else None
    if not mode or not stat.S_ISREG(mode.st_mode) or mode.st_nlink != 1:
        raise ValueError('Mobile artifact is missing or linked.')
    if mode.st_size != item['bytes'] or file_hash(path) != item['sha256']:
        raise ValueError('Mobile artifact changed since the build. Build it again.')
    return path, item


def log(project_id, build_id):
    get(project_id, build_id)
    path = directory(project_id, build_id) / 'build.log'
    if path.is_symlink():
        raise ValueError('Invalid mobile build log.')
    return agent.redact(path.read_text()[-MAX_LOG:]) if path.is_file() else ''


def compile_native(work, data, cancelled, deadline, log_path, phase):
    gen = generator()
    gen.do_init(SimpleNamespace(**{key: data[key] for key in ('origin', 'name', 'app_id', 'version')},
                                output=str(work), force=False, debuggable=False))
    # Remove generator convenience hooks from the build input. Never copy source,
    # package.json, Gradle/Xcode scripts or plugins from the agent's project.
    package = json.loads((work / 'package.json').read_text())
    package['scripts'] = {}
    (work / 'package.json').write_text(json.dumps(package))
    env = build_environment(work)
    sdk = android_sdk()
    if sdk:
        env.update(ANDROID_HOME=str(sdk), ANDROID_SDK_ROOT=str(sdk))
    def run(argv, cwd=work):
        return command(argv, cwd, env, cancelled, deadline, log_path)
    phase('Installing pinned Capacitor tooling')
    run(['npm', 'install', '--ignore-scripts', '--no-audit', '--no-fund', '--fetch-timeout=30000',
         '--fetch-retries=1', '--registry=https://registry.npmjs.org'])
    cap = [shutil.which('node'), work / 'node_modules/@capacitor/cli/bin/capacitor']
    platform_name = 'android' if data['target'] in {'apk', 'aab'} else 'ios'
    phase('Generating ' + platform_name + ' project')
    run([*cap, 'add', platform_name])
    # Generate the real icons before hardening, so the artifact carries the app's own
    # branding rather than Capacitor's placeholder logo.
    if data.get('icon_source'):
        phase('Generating app icons')
        gen.do_icons(SimpleNamespace(source=data['icon_source'],
                                     background=data.get('icon_background', '#FFFFFF'),
                                     output=str(work)))
    gen.do_harden(SimpleNamespace(output=str(work)))
    # Sync the final config/assets after hardening, then check copied native config.
    run([*cap, 'sync', platform_name])
    if gen.do_check(SimpleNamespace(output=str(work), require_icons=bool(data.get('icon_source')))):
        raise ValueError('Mobile configuration checks failed.')
    if data['target'] in {'apk', 'aab'}:
        gradle = work / 'android/app/build.gradle'
        gradle.write_text(re.sub(r'versionCode\s+\d+', 'versionCode ' + str(data['build_number']), gradle.read_text(), count=1))
        if data['target'] == 'apk':
            phase('Compiling Android APK')
            run(['bash', 'gradlew', '--no-daemon', '--console=plain', 'assembleDebug'], work / 'android')
            output = work / 'android/app/build/outputs/apk/debug/app-debug.apk'
            phase('Verifying APK signature')
            signer = sorted(sdk.glob('build-tools/*/apksigner'),
                            key=lambda p: tuple(int(n) for n in re.findall(r'\d+', p.parent.name)))[-1]
            run([signer, 'verify', '--verbose', output])
            return output

        # Applied as a separate script rather than patching the generated
        # build.gradle, so a change to Capacitor's template cannot silently break
        # the injection and leave an unsigned release.
        (work / 'android/app/signing.gradle').write_text(SIGNING_GRADLE)
        with (work / 'android/app/build.gradle').open('a') as stream:
            stream.write("\napply from: 'signing.gradle'\n")
        secrets = (data['store_password'], data['key_password'])
        env.update(FOUNDRY_KEYSTORE=data['keystore_path'], FOUNDRY_KEY_ALIAS=data['key_alias'],
                   FOUNDRY_STORE_PASSWORD=data['store_password'], FOUNDRY_KEY_PASSWORD=data['key_password'])
        phase('Compiling signed Android app bundle')
        command(['bash', 'gradlew', '--no-daemon', '--console=plain', 'bundleRelease'],
                work / 'android', env, cancelled, deadline, log_path, secrets)
        output = work / 'android/app/build/outputs/bundle/release/app-release.aab'
        if not output.is_file():
            raise ValueError('Gradle did not produce a release bundle. Check the build log.')
        phase('Verifying upload-key signature')
        # Trust only the selected upload certificate, including self-signed keys.
        # Keep strict verification: unsigned/tampered entries and a different
        # signing alias must still fail. Password values never enter argv.
        command(['jarsigner', '-verify', '-strict', '-keystore', data['keystore_path'],
                 '-storepass:env', 'FOUNDRY_STORE_PASSWORD', output, data['key_alias']],
                work / 'android', env, cancelled, deadline, log_path, secrets)
        return output
    import plistlib
    options = work / 'ExportOptions.plist'
    with options.open('wb') as stream:
        plistlib.dump({'method': data['export_method'], 'teamID': data['team_id'],
                      'signingStyle': 'automatic', 'destination': 'export', 'uploadSymbols': False,
                      'manageAppVersionAndBuildNumber': False}, stream)
    archive = work / 'App.xcarchive'
    phase('Archiving and signing iOS app')
    run(['xcodebuild', '-project', 'ios/App/App.xcodeproj', '-scheme', 'App',
         '-configuration', 'Release', '-destination', 'generic/platform=iOS', '-archivePath', archive,
         '-allowProvisioningUpdates', 'DEVELOPMENT_TEAM=' + data['team_id'], 'CODE_SIGN_STYLE=Automatic',
         'CURRENT_PROJECT_VERSION=' + str(data['build_number']), 'MARKETING_VERSION=' + data['version'], 'archive'])
    apps = list((archive / 'Products/Applications').glob('*.app'))
    if len(apps) != 1:
        raise ValueError('Xcode did not produce a single archived app.')
    run(['codesign', '--verify', '--deep', '--strict', apps[0]])
    phase('Exporting signed IPA')
    export = work / 'export'
    run(['xcodebuild', '-exportArchive', '-archivePath', archive, '-exportPath', export,
         '-exportOptionsPlist', options, '-allowProvisioningUpdates'])
    outputs = list(export.glob('*.ipa'))
    if len(outputs) != 1:
        raise ValueError('Xcode did not export an IPA. Check the signing profile and export method.')
    return outputs[0]


def execute(project_id, run_id, cancelled, data):
    folder = directory(project_id, run_id)
    folder.mkdir(parents=True, mode=0o700)
    folder.parent.chmod(0o700)
    work = folder / 'work'
    # Only these keys are persisted, so signing passwords cannot reach build.json.
    record = {key: data[key] for key in ('target', 'name', 'origin', 'app_id', 'version', 'build_number', 'source_digest')}
    record.update(id=run_id, project_id=project_id, status='running', phase='Preparing build', created_at=db.now())
    if data['target'] == 'aab':
        # Which key signed it matters on upload; the alias is not secret.
        record['key_alias'] = data['key_alias']
    write_record(folder, record)
    def phase(text):
        check_cancel(cancelled)
        record['phase'] = text
        write_record(folder, record)
        db.event(run_id, 'status', text)
    try:
        check_cancel(cancelled)
        if files.digest(sandbox.source_dir(project_id)) != data['source_digest']:
            raise ValueError('Project changed. Refresh before starting a mobile build.')
        output = compile_native(work, data, cancelled, time.monotonic() + BUILD_SECONDS, folder / 'build.log', phase)
        check_cancel(cancelled)
        inspect_artifact(output, data['target'])
        destination = folder / ('app.' + data['target'])
        shutil.copyfile(output, destination)
        destination.chmod(0o600)
        record.update(status='completed', phase='Ready to download', bytes=destination.stat().st_size,
                      sha256=file_hash(destination), filename=data['app_id'] + '-' + data['version'] +
                      {'apk': '-debug.apk', 'aab': '-release.aab', 'ipa': '.ipa'}[data['target']])
        check_cancel(cancelled)
        write_record(folder, record)
        db.event(run_id, 'status', 'Mobile artifact ready to download. Device testing is still required.')
    except BaseException as exc:
        record.update(status='cancelled' if isinstance(exc, InterruptedError) else 'failed',
                      phase=agent.redact(exc)[-4000:])
        write_record(folder, record)
        (folder / ('app.' + data['target'])).unlink(missing_ok=True)
        raise
    finally:
        if work.exists():
            try:
                shutil.rmtree(work)
            except OSError:
                record['cleanup_note'] = 'Temporary native build files need manual cleanup in the private build folder.'
                write_record(folder, record)
